const USER_ACTION_TYPES = {
    CHECK_USER_SESSION: 'user/CHECK_USER_SESSION',
    GOOGLE_SIGN_IN_START: 'user/GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START: 'user/EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCES: 'user/SIGN_IN_SUCCES',
    SIGN_IN_FAILURE: 'user/SIGN_IN_FAILURE'
  };

  export default USER_ACTION_TYPES